# Generated by Django 5.2.3 on 2025-07-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Charge', 'Charge'), ('Personal Loan', 'Personal Loan'), ('Vehicle Loan', 'Vehicle Loan')], max_length=20),
        ),
    ]
