# Generated by Django 5.2.3 on 2025-07-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_transaction_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytype',
            name='name',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income'), ('Transfer', 'Transfer'), ('Misc', 'Misc'), ('Bank Fees', 'Bank Fees')], max_length=50),
        ),
    ]
