# Generated by Django 5.2.3 on 2025-07-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_categorytype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('TRANSFER', 'Transfer'), ('CARRYOVER', 'Carryover'), ('LOAN_PAYMENT', 'Loan or Credit Card Payment'), ('CREDIT', 'Credit (e.g. rebate, return)'), ('INTEREST', 'Interest'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
    ]
