# Generated by Django 5.2.3 on 2025-07-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0009_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('EXPENSE', 'Expense'), ('INCOME', 'Income'), ('TRANSFER', 'Transfer'), ('CARRYOVER', 'Carryover'), ('CC_PAYMENT', 'Credit Card Payment'), ('LOAN_PAYMENT', 'Loan Payment'), ('CREDIT', 'Credit (e.g. rebate, return)'), ('INTEREST', 'Interest'), ('BANK_FEES', 'Bank Fees'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
    ]
