# Generated by Django 5.2.3 on 2025-07-14 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0010_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='infer_transaction_type',
            fields=[
                ('account_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budget.account')),
            ],
            bases=('budget.account',),
        ),
        migrations.AlterField(
            model_name='categorytype',
            name='name',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income'), ('Transfer', 'Transfer'), ('Debt Repayment', 'Debt Repayment')], max_length=50),
        ),
    ]
