# Generated by Django 5.2.3 on 2025-07-14 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0011_infer_transaction_type_alter_categorytype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytype',
            name='name',
            field=models.CharField(choices=[('Expense', 'Expense'), ('Income', 'Income'), ('Transfer', 'Transfer'), ('Debt Repayment', 'Debt Repayment'), ('Savings', 'Savings')], max_length=50),
        ),
    ]
