# Generated by Django 5.2.3 on 2025-07-15 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0012_alter_categorytype_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transfer',
        ),
        migrations.DeleteModel(
            name='CategoryType',
        ),
    ]
