# Generated by Django 5.2.3 on 2025-07-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0013_remove_category_category_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ('name',)},
        ),
    ]
