# Generated by Django 5.2.3 on 2025-07-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0014_alter_account_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_expense',
            field=models.BooleanField(default=True),
        ),
    ]
