# Generated by Django 5.2.3 on 2025-07-15 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0015_category_is_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.category'),
        ),
    ]
