# Generated by Django 5.2.3 on 2025-07-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0016_transaction_expense'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='expense',
            new_name='is_expense',
        ),
    ]
