# Generated by Django 5.2.3 on 2025-07-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0017_rename_expense_transaction_is_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_expense',
        ),
    ]
