# Generated by Django 5.2.3 on 2025-07-16 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0018_remove_transaction_is_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_income',
            field=models.BooleanField(default=False),
        ),
    ]
