# Generated by Django 5.2.3 on 2025-09-04 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0019_category_is_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.transfer'),
        ),
        migrations.AlterUniqueTogether(
            name='transaction',
            unique_together={('transfer', 'account')},
        ),
    ]
