# Generated by Django 5.2.8 on 2025-12-18 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0021_gigshift_gigcompany_gigcompanyentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('icloud', 'iCloud (CalDAV)'), ('outlook', 'Outlook (Graph)')], max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('credentials_json', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_calendar_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('timezone', models.CharField(default='America/New_York', max_length=64)),
                ('is_primary', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.calendaraccount')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_event_id', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('start_dt', models.DateTimeField()),
                ('end_dt', models.DateTimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('status', models.CharField(default='confirmed', max_length=32)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider_etag', models.CharField(blank=True, max_length=255)),
                ('provider_last_modified', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budget.calendarsource')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'start_dt'], name='budget_cale_user_id_d76103_idx'), models.Index(fields=['external_event_id'], name='budget_cale_externa_154a8a_idx')],
            },
        ),
    ]
