# Generated by Django 5.2.8 on 2025-12-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0026_calendaraccount_calendarsource_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarsource',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calendarsource',
            name='sync_cursor',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
