# Generated by Django 5.2.8 on 2025-12-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0027_calendarsource_last_synced_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='person',
            field=models.CharField(choices=[('mike', 'Mike'), ('wife', 'Stef'), ('kid1', 'Max'), ('kid2', 'Leo')], default='mike', max_length=20),
        ),
    ]
