# Generated by Django 5.2.8 on 2025-12-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0028_calendarevent_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('special_type', models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('holiday', 'Holiday'), ('milestone', 'Milestone'), ('reminder', 'Reminder')], default='reminder', max_length=20)),
                ('person', models.CharField(blank=True, max_length=20)),
                ('recurring_yearly', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('color_key', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
