# Generated by Django 5.2.8 on 2025-12-22 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0029_calendarspecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(default='normal', max_length=20),
        ),
    ]
