# Generated by Django 5.2.8 on 2025-12-22 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0030_calendarevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.calendarsource'),
        ),
    ]
