# Generated by Django 5.2.8 on 2025-12-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0031_alter_calendarevent_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarspecial',
            name='person',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
