# Generated by Django 5.2.8 on 2025-12-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0032_alter_calendarspecial_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarRuleSpecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('rule_key', models.CharField(choices=[('easter', 'Easter (Western)'), ('thanksgiving_us', 'Thanksgiving (US)'), ('mothers_day_us', "Mother's Day (US)"), ('fathers_day_us', "Father's Day (US)"), ('memorial_day_us', 'Memorial Day (US)'), ('labor_day_us', 'Labor Day (US)'), ('mlk_day_us', 'MLK Day (US)'), ('presidents_day_us', 'Presidents Day (US)')], max_length=50)),
                ('special_type', models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('holiday', 'Holiday'), ('milestone', 'Milestone'), ('reminder', 'Reminder')], default='holiday', max_length=20)),
                ('person', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('color_key', models.CharField(blank=True, max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
