# Generated by Django 5.2.8 on 2025-12-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0033_calendarrulespecial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarrulespecial',
            name='title_override',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
