# Generated by Django 5.2.8 on 2026-01-05 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0034_calendarrulespecial_title_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigcompany',
            name='income_category',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='last_edited_by',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='gigcompany',
            name='income_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.subcategory'),
        ),
        migrations.AlterField(
            model_name='calendarrulespecial',
            name='rule_key',
            field=models.CharField(choices=[('easter', 'Easter (Western)'), ('good_friday', 'Good Friday'), ('thanksgiving_us', 'Thanksgiving (US)'), ('mothers_day_us', "Mother's Day (US)"), ('fathers_day_us', "Father's Day (US)"), ('memorial_day_us', 'Memorial Day (US)'), ('labor_day_us', 'Labor Day (US)'), ('mlk_day_us', 'MLK Day (US)'), ('presidents_day_us', 'Presidents Day (US)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gigcompanyentry',
            name='earnings_before_tips',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gigcompanyentry',
            name='tips_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='gigshift',
            name='gas_price',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.CreateModel(
            name='MileageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(help_text='Date this rate becomes effective (inclusive).')),
                ('rate', models.DecimalField(decimal_places=3, help_text='Deduction per mile in dollars, e.g. 0.670', max_digits=5)),
                ('note', models.CharField(blank=True, help_text="Optional note (e.g. 'IRS 2025 standard rate')", max_length=100)),
            ],
            options={
                'verbose_name': 'Mileage rate',
                'verbose_name_plural': 'Mileage rates',
                'ordering': ['-effective_date'],
                'constraints': [models.UniqueConstraint(fields=('effective_date',), name='unique_mileage_rate_per_effective_date')],
            },
        ),
    ]
