# Generated by Django 5.2.8 on 2026-01-06 14:53

from django.db import migrations
import datetime


def seed_calendar_holidays(apps, schema_editor):
    CalendarSpecial = apps.get_model("budget", "CalendarSpecial")
    CalendarRuleSpecial = apps.get_model("budget", "CalendarRuleSpecial")

    # -------------------------
    # CalendarSpecial (fixed dates)
    # Match by (title, special_type) so it can update date/color/etc if changed later.
    # -------------------------
    specials = [
        # title, date, special_type, recurring_yearly, color_key, notes, person
        ("Christmas Eve", datetime.date(2025, 12, 24), "holiday", True, "red", "", ""),
        ("Christmas Day", datetime.date(2025, 12, 25), "holiday", True, "red", "", ""),
        ("4th of July", datetime.date(2026, 7, 4), "holiday", True, "red", "", ""),
        ("Veteran's Day", datetime.date(2025, 11, 11), "holiday", True, "red", "", ""),
        ("Valentine's Day", datetime.date(2025, 2, 14), "holiday", True, "red", "", ""),
        ("St. Patrick's Day", datetime.date(2025, 3, 17), "holiday", True, "red", "", ""),
        ("Halloween", datetime.date(2025, 10, 31), "holiday", True, "red", "", ""),
        ("New Year's Day", datetime.date(2026, 1, 1), "holiday", True, "red", "", ""),
    ]

    for title, dt, special_type, recurring_yearly, color_key, notes, person in specials:
        obj, _created = CalendarSpecial.objects.get_or_create(
            title=title,
            special_type=special_type,
            defaults={
                "date": dt,
                "recurring_yearly": recurring_yearly,
                "notes": notes,
                "color_key": color_key,
                "person": person,
            },
        )

        # Keep it idempotent: ensure fields match your intended defaults
        changed = False
        if getattr(obj, "date", None) != dt:
            obj.date = dt
            changed = True
        if getattr(obj, "recurring_yearly", None) != recurring_yearly:
            obj.recurring_yearly = recurring_yearly
            changed = True
        if getattr(obj, "notes", "") != (notes or ""):
            obj.notes = notes or ""
            changed = True
        if getattr(obj, "color_key", "") != (color_key or ""):
            obj.color_key = color_key or ""
            changed = True
        if getattr(obj, "person", "") != (person or ""):
            obj.person = person or ""
            changed = True

        if changed:
            obj.save()

    # -------------------------
    # CalendarRuleSpecial (rule-based holidays)
    # Match by rule_key (unique key) so it updates cleanly if changed later.
    # -------------------------
    rules = [
        # rule_key, special_type, color_key, is_enabled, title, title_override, notes, person
        ("easter", "holiday", "red", True, "", "", "", ""),
        ("good_friday", "holiday", "red", True, "", "", "", ""),
        ("thanksgiving_us", "holiday", "red", True, "", "", "", ""),
        ("mothers_day_us", "holiday", "red", True, "", "", "", ""),
        ("fathers_day_us", "holiday", "red", True, "", "", "", ""),
        ("labor_day_us", "holiday", "red", True, "", "", "", ""),
        ("memorial_day_us", "holiday", "red", True, "", "", "", ""),
        ("mlk_day_us", "holiday", "red", True, "", "", "", ""),
        ("presidents_day_us", "holiday", "red", True, "", "", "", ""),
    ]

    for rule_key, special_type, color_key, is_enabled, title, title_override, notes, person in rules:
        obj, _created = CalendarRuleSpecial.objects.get_or_create(
            rule_key=rule_key,
            defaults={
                "title": title,
                "special_type": special_type,
                "person": person,
                "notes": notes,
                "color_key": color_key,
                "is_enabled": is_enabled,
                "title_override": title_override,
            },
        )

        # Idempotent updates
        changed = False
        if getattr(obj, "title", "") != (title or ""):
            obj.title = title or ""
            changed = True
        if getattr(obj, "special_type", "") != (special_type or ""):
            obj.special_type = special_type or ""
            changed = True
        if getattr(obj, "person", "") != (person or ""):
            obj.person = person or ""
            changed = True
        if getattr(obj, "notes", "") != (notes or ""):
            obj.notes = notes or ""
            changed = True
        if getattr(obj, "color_key", "") != (color_key or ""):
            obj.color_key = color_key or ""
            changed = True
        if getattr(obj, "is_enabled", True) != is_enabled:
            obj.is_enabled = is_enabled
            changed = True
        if getattr(obj, "title_override", "") != (title_override or ""):
            obj.title_override = title_override or ""
            changed = True

        if changed:
            obj.save()


def unseed_calendar_holidays(apps, schema_editor):
    CalendarSpecial = apps.get_model("budget", "CalendarSpecial")
    CalendarRuleSpecial = apps.get_model("budget", "CalendarRuleSpecial")

    # Remove only what we seeded (protects user-created records)
    seeded_special_titles = [
        "Christmas Eve",
        "Christmas Day",
        "4th of July",
        "Veteran's Day",
        "Valentine's Day",
        "St. Patrick's Day",
        "Halloween",
        "New Year's Day",
    ]
    CalendarSpecial.objects.filter(
        special_type="holiday",
        title__in=seeded_special_titles,
    ).delete()

    seeded_rule_keys = [
        "easter",
        "good_friday",
        "thanksgiving_us",
        "mothers_day_us",
        "fathers_day_us",
        "labor_day_us",
        "memorial_day_us",
        "mlk_day_us",
        "presidents_day_us",
    ]
    CalendarRuleSpecial.objects.filter(rule_key__in=seeded_rule_keys).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("budget", "0035_remove_gigcompany_income_category_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_calendar_holidays, unseed_calendar_holidays),
    ]