# Generated by Django 5.2.8 on 2026-01-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0036_seed_calendar_holidays'),
        ('calendar_app', '0001_initial' ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # DO NOTHING to DB (don’t drop tables)
            ],
            state_operations=[
                migrations.DeleteModel(name="CalendarEvent"),
                migrations.DeleteModel(name="CalendarSource"),
                migrations.DeleteModel(name="CalendarAccount"),
                migrations.DeleteModel(name="CalendarSpecial"),
                migrations.DeleteModel(name="CalendarRuleSpecial"),
            ],
        ),
    ]
