# Generated by Django 5.2.8 on 2026-01-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0037_remove_calendaraccount_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gigcompany',
            name='income_subcategory',
        ),
        migrations.RemoveField(
            model_name='gigcompany',
            name='payout_account',
        ),
        migrations.RemoveField(
            model_name='gigcompanyentry',
            name='company',
        ),
        migrations.RemoveField(
            model_name='gigcompanyentry',
            name='income_transaction',
        ),
        migrations.RemoveField(
            model_name='gigcompanyentry',
            name='shift',
        ),
        migrations.DeleteModel(
            name='MileageRate',
        ),
        migrations.DeleteModel(
            name='GigCompany',
        ),
        migrations.DeleteModel(
            name='GigCompanyEntry',
        ),
        migrations.DeleteModel(
            name='GigShift',
        ),
    ]
