# Generated by Django 5.2.8 on 2026-01-16 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0038_remove_gigcompany_income_subcategory_and_more'),
    ]

    operations = [
      
    ]