# Generated by Django 5.2.8 on 2026-02-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
