# Generated by Django 5.2.8 on 2026-02-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker', '0002_application_applied_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['-applied_at', '-applied_date', '-created_at']},
        ),
    ]
