# Generated by Django 5.2.8 on 2026-02-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobtracker', '0003_alter_application_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communication',
            options={'ordering': ['-when', '-id']},
        ),
    ]
