# Generated by Django 5.2.8 on 2026-01-14 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("budget", "0036_seed_calendar_holidays"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # DO NOTHING to DB (don’t create tables)
            ],
            state_operations=[
                migrations.CreateModel(
                    name='CalendarRuleSpecial',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=255)),
                        ('rule_key', models.CharField(choices=[('easter', 'Easter (Western)'), ('good_friday', 'Good Friday'), ('thanksgiving_us', 'Thanksgiving (US)'), ('mothers_day_us', "Mother's Day (US)"), ('fathers_day_us', "Father's Day (US)"), ('memorial_day_us', 'Memorial Day (US)'), ('labor_day_us', 'Labor Day (US)'), ('mlk_day_us', 'MLK Day (US)'), ('presidents_day_us', 'Presidents Day (US)')], max_length=50)),
                        ('title_override', models.CharField(blank=True, max_length=255)),
                        ('special_type', models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('holiday', 'Holiday'), ('milestone', 'Milestone'), ('reminder', 'Reminder')], default='holiday', max_length=20)),
                        ('person', models.CharField(blank=True, max_length=50)),
                        ('notes', models.TextField(blank=True)),
                        ('color_key', models.CharField(blank=True, max_length=20)),
                        ('is_enabled', models.BooleanField(default=True)),
                    ],
                ),
                migrations.CreateModel(
                    name='CalendarSpecial',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=255)),
                        ('date', models.DateField()),
                        ('special_type', models.CharField(choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('holiday', 'Holiday'), ('milestone', 'Milestone'), ('reminder', 'Reminder')], default='reminder', max_length=20)),
                        ('person', models.CharField(blank=True, max_length=50)),
                        ('recurring_yearly', models.BooleanField(default=True)),
                        ('notes', models.TextField(blank=True)),
                        ('color_key', models.CharField(blank=True, max_length=20)),
                    ],
                ),
                migrations.CreateModel(
                    name='CalendarAccount',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('provider', models.CharField(choices=[('google', 'Google'), ('icloud', 'iCloud (CalDAV)'), ('outlook', 'Outlook (Graph)')], max_length=20)),
                        ('display_name', models.CharField(blank=True, max_length=120)),
                        ('credentials_json', models.JSONField(default=dict)),
                        ('is_active', models.BooleanField(default=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                ),
                migrations.CreateModel(
                    name='CalendarSource',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('external_calendar_id', models.CharField(max_length=255)),
                        ('name', models.CharField(max_length=255)),
                        ('timezone', models.CharField(default='America/New_York', max_length=64)),
                        ('is_primary', models.BooleanField(default=False)),
                        ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                        ('sync_cursor', models.CharField(blank=True, max_length=255)),
                        ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.calendaraccount')),
                    ],
                ),
                migrations.CreateModel(
                    name='CalendarEvent',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('external_event_id', models.CharField(blank=True, max_length=255)),
                        ('title', models.CharField(max_length=255)),
                        ('location', models.CharField(blank=True, max_length=255)),
                        ('notes', models.TextField(blank=True)),
                        ('start_dt', models.DateTimeField()),
                        ('end_dt', models.DateTimeField()),
                        ('all_day', models.BooleanField(default=False)),
                        ('status', models.CharField(default='confirmed', max_length=32)),
                        ('event_type', models.CharField(default='normal', max_length=20)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('created_by', models.CharField(blank=True, default='', max_length=20)),
                        ('last_edited_by', models.CharField(blank=True, default='', max_length=20)),
                        ('person', models.CharField(choices=[('mike', 'Mike'), ('wife', 'Stef'), ('kid1', 'Max'), ('kid2', 'Leo')], default='mike', max_length=20)),
                        ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                        ('provider_etag', models.CharField(blank=True, max_length=255)),
                        ('provider_last_modified', models.DateTimeField(blank=True, null=True)),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                        ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calendar_app.calendarsource')),
                    ],
                    
             ),
            ],
        ),
    ]