# Generated by Django 5.2.8 on 2026-01-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='calendaraccount',
            table='calendar_app_calendaraccount',
        ),
        migrations.AlterModelTable(
            name='calendarevent',
            table='calendar_app_calendarevent',
        ),
        migrations.AlterModelTable(
            name='calendarrulespecial',
            table='calendar_app_calendarrulespecial',
        ),
        migrations.AlterModelTable(
            name='calendarsource',
            table='calendar_app_calendarsource',
        ),
        migrations.AlterModelTable(
            name='calendarspecial',
            table='calendar_app_calendarspecial',
        ),
    ]
