# Generated by Django 5.2.8 on 2026-01-16 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
       
    ]
