# Generated by Django 5.2.8 on 2026-01-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_alter_calendaraccount_table_and_more'),
    ]

    operations = [
        
    ]
