# Generated by Django 5.2.8 on 2026-02-06 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_alter_calendaraccount_table_and_more'),
    ]

    operations = [
       
    ]
