# Generated by Django 5.2.8 on 2026-02-06 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_alter_calendaraccount_table_and_more'),
    ]
    