# Generated by Django 5.2.8 on 2026-08-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_calendarevent_recurrence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Does not repeat'), ('daily', 'Daily'), ('weekdays', 'Weekdays (Mon-Fri)'), ('weekly', 'Weekly'), ('biweekly', 'Every 2 weeks'), ('monthly', 'Monthly'), ('bimonthly', 'Every 2 months'), ('yearly', 'Yearly')], default='none', max_length=20),
        ),
    ]
