# Generated by Django 5.2.8 on 2026-01-16 19:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0038_remove_gigcompany_income_subcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GigShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('miles', models.DecimalField(decimal_places=2, max_digits=7)),
                ('mpg', models.DecimalField(decimal_places=1, max_digits=4)),
                ('gas_price', models.DecimalField(decimal_places=3, max_digits=4)),
                ('company_mix_note', models.CharField(blank=True, help_text='Optional (e.g. WM/DD/UE)', max_length=50)),
                ('mileage_deduction_rate', models.DecimalField(decimal_places=2, default=0.67, max_digits=4)),
            ],
            options={
                'db_table': 'budget_gigshift',
            },
        ),
        migrations.CreateModel(
            name='MileageRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(help_text='Date this rate becomes effective (inclusive).')),
                ('rate', models.DecimalField(decimal_places=3, help_text='Deduction per mile in dollars, e.g. 0.670', max_digits=5)),
                ('note', models.CharField(blank=True, help_text="Optional note (e.g. 'IRS 2025 standard rate')", max_length=100)),
            ],
            options={
                'db_table': 'budget_mileagerate',
            },
        ),
        migrations.CreateModel(
            name='GigCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('income_subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.subcategory')),
                ('payout_account', models.ForeignKey(help_text="Which account receives this company's payouts", on_delete=django.db.models.deletion.PROTECT, to='budget.account')),
            ],
            options={
                'db_table': 'budget_gigcompany',
            },
        ),
        migrations.CreateModel(
            name='GigCompanyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveries', models.IntegerField()),
                ('tips_count', models.IntegerField(help_text='Number of deliveries that had a tip')),
                ('tips_amount', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('earnings_before_tips', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('gross_earnings', models.DecimalField(decimal_places=2, help_text='Base pay + tips for this company during this shift', max_digits=7)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gig_entries', to='gigs.gigcompany')),
                ('income_transaction', models.OneToOneField(blank=True, help_text='Automatically-created income transaction for this company+shift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gig_income_entry', to='budget.transaction')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_entries', to='gigs.gigshift')),
            ],
            options={
                'db_table': 'budget_gigcompanyentry',
                'ordering': ['company__code'],
            },
        ),
    ]
